### ISSUE TITLE
hilfe

### ISSUE THREAD

**Issue by raetz023** [Coralise/CustomBansPlus#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Hallo ich habe ein problem ich weiß nicht nicht wie ich die Meldung weg bekomme kenne mich da nicht so aus 
**Screenshots**
![Minecraft_ 1 16 5 - Mehrspieler (Drittanbieter-Server) 12 05 2021 17_34_03](https://user-images.githubusercontent.com/84150353/118170701-b4360f80-b42a-11eb-85b6-306d3d9c6674.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Coralise** [comment]
Do you have any other information? You just posted an image and didn't add any other details. Sie können unserem Discord-Server beitreten und wir können dort sprechen. [Discord Link](https://discord.gg/invite/bu4kqJY7V5)
