### ISSUE TITLE
Console's UUID

### ISSUE THREAD

**Issue by cactus889** [Coralise/CustomBansPlus#3]
**Describe the bug**
If the database contains the staff who issued the mute - console, then when the server restarts, there will be an error and CBP doesn't work.

**To Reproduce**
1. Connect plugin to mysql
2. Run command 'mute nickname {any time} {any reason}' from console
3. Restart server
4. See error https://pastebin.com/LUbagHYQ

**Expected behavior**
No errors and normal plugin operation.

**Screenshots**
A window with mysql.

**Versions:**
 - Java: 16
 - Server: pufferfish 1.17.1
 - Plugin: 3.3.16.2
![Screenshot_67](https://user-images.githubusercontent.com/91200325/147588314-aa7aa5c2-acae-4cf3-b896-9bc2dc3fe574.png)

**Comment by Coralise** [comment]
This is now fixed, thanks for reporting!
