### ISSUE TITLE
Reports GUI does not perform actions

### ISSUE THREAD

**Issue by yiffyrusdev** [Coralise/CustomBansPlus#4]
**Describe the bug**
In the CBP GUI I can switch to the specific player's reports page, then to "archieve" page. But any action with red_wool block in the player's page does not do enything. Report could not be marked as "solved", could not be sent to "archieve", could not be "removed" etc.

**To Reproduce**
1. Run /reports list
2. Click on any skull
3. Click on red_wool block / Shift+Rclick / Shift+Lclick / press Q
4. See that nothing changed nether in GUI nor in report status
5. No errors/messages in the server console

**Expected behavior**
When red_wool block is clicked somehow in the player's page of GUI according action on report is performed (resolved, archieved, deleted etc)

**Setup**
 - Server: papermc 1.18.2 
 - CBP: 3.3.19.4
 - Java: java-17-openjdk
 - hopper.disable-move-event is "false"
 - Tested permission level: op
 
 If you need any further information, i'll be glad to provide.

**Comment by Coralise** [comment]
This is noted, thank you for submitting a bug report 😄

**Comment by yiffyrusdev** [comment]
Thank you! I really want to support development of this plugin - it is literally awesome!
But, unfortunatelly, its very hard to use at the moment

**Comment by RandomKittenCat** [comment]
i have this same issue

**Comment by Coralise** [comment]
Issue solved! Took me a while to release the patch though lol, sorry!
**Patched @ CBP v3.3.20**
Huge thank you to everyone who reported 😀
